import type { ChatMessage, ReActParsedStep, ToolExecution } from "./types";
import { executeLocalTool, localToolDefinitions } from "./tools";

export const sanitizeModelPayload = (value: unknown): unknown => Array.isArray(value) ? value.map(sanitizeModelPayload) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, key === "reasoning_content" ? "[redacted by AgentXRay: model reasoning is outside runtime inspection scope]" : sanitizeModelPayload(entry)])) : value;
export const reactToolGuide = localToolDefinitions.map((tool) => `- ${tool.function.name}: ${tool.function.description} Parameters: ${JSON.stringify(tool.function.parameters)}`).join("\n");
export const extractJsonObject = (value: string) => { const start = value.indexOf("{"); const end = value.lastIndexOf("}"); if (start < 0 || end < start) throw new Error("Action Input must contain a JSON object."); return value.slice(start, end + 1); };
export const parseReActResponse = (content: string): ReActParsedStep => {
  const finalMatch = content.match(/Final Answer\s*:\s*([\s\S]*)/i); if (finalMatch?.[1]?.trim()) return { thought: content.match(/Thought\s*:\s*([\s\S]*?)(?:Final Answer\s*:|$)/i)?.[1]?.trim(), finalAnswer: finalMatch[1].trim() };
  const actionMatch = content.match(/Action\s*:\s*([a-zA-Z0-9_-]+)/i); const inputMatch = content.match(/Action Input\s*:\s*([\s\S]*)/i);
  if (!actionMatch?.[1] || !inputMatch?.[1]) return { thought: content.match(/Thought\s*:\s*([\s\S]*)/i)?.[1]?.trim(), parseError: 'Expected either "Final Answer: ..." or both "Action: <tool>" and "Action Input: {...}".' };
  try { return { thought: content.match(/Thought\s*:\s*([\s\S]*?)(?:Action\s*:|$)/i)?.[1]?.trim(), action: actionMatch[1].trim(), actionInput: JSON.parse(extractJsonObject(inputMatch[1])) }; } catch (error) { return { action: actionMatch[1].trim(), parseError: error instanceof Error ? error.message : "Could not parse Action Input." }; }
};
export const createReActToolExecution = (round: number, parsed: ReActParsedStep): ToolExecution => { const toolCall = { id: `react-round-${round}`, type: "function" as const, function: { name: parsed.action ?? "unknown", arguments: JSON.stringify(parsed.actionInput ?? {}) } }; return parsed.parseError ? { toolCall, name: toolCall.function.name, arguments: parsed.actionInput ?? {}, content: JSON.stringify({ error: parsed.parseError }), ok: false, error: parsed.parseError } : executeLocalTool(toolCall); };
export const createObservationMessage = (execution: ToolExecution): { role: "user"; content: string } => ({ role: "user", content: `Observation: ${execution.content}\n\nContinue the ReAct loop. If the observation is enough, respond with "Final Answer: ...". Otherwise use exactly one more Action.` });
export const finalAnswerFromContent = (content: string) => content.match(/Final Answer\s*:\s*([\s\S]*)/i)?.[1]?.trim() ?? content.trim();
export const plannerSystemPrompt = `You are a planner. Break the user's task into a sequence of concrete, executable steps. Each step must be a single well-defined action that can be accomplished with the available tools (calculate, get_current_datetime) or through reasoning. Do NOT solve the task yourself — only produce the plan.\n\nOutput ONLY a JSON object with this exact structure (no other text):\n{\n  "plan": [\n    "Step 1 description",\n    "Step 2 description"\n  ]\n}`;
export const executorSystemPrompt = (step: string, plan: string[], task: string) => `You are an executor. Execute the current step of the plan using the available tools when necessary. After receiving tool results, provide a concise step result.\n\nOriginal task: ${task}\n\nFull plan:\n${plan.map((s, i) => `${i + 1}. ${s}`).join("\n")}\n\nCurrent step: ${step}\n\nUse tools if this step requires computation or data lookup. When done, state your result clearly.`;
export const synthesizerSystemPrompt = (task: string, plan: string[], results: string[]) => `You are a synthesizer. Based on the original task, the execution plan, and the results of each step, produce a comprehensive final answer. Combine all step results into a single coherent response.\n\nOriginal task: ${task}\n\nPlan and results:\n${plan.map((s, i) => `Step ${i + 1}: ${s}\nResult: ${results[i] ?? "Not completed"}`).join("\n\n")}\n\nNow produce the final answer for the user.`;
export const extractJsonObjectFromText = (text: string): Record<string, unknown> | null => { const start = text.indexOf("{"); const end = text.lastIndexOf("}"); if (start < 0 || end < start) return null; try { const parsed: unknown = JSON.parse(text.slice(start, end + 1)); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null; } catch { return null; } };
export const parsePlan = (content: string): string[] => { const json = extractJsonObjectFromText(content); if (json && Array.isArray(json.plan)) return json.plan.filter((s): s is string => typeof s === "string" && !!s.trim()); const lines = content.split("\n").filter((line) => /^\d+[.)]\s*/.test(line.trim())); return lines.length ? lines.map((line) => line.replace(/^\d+[.)]\s*/, "").trim()).filter(Boolean) : [content.trim()]; };
