import { assertRunnable, runChatCompletion } from "./client";
import { executorSystemPrompt, parsePlan, plannerSystemPrompt, synthesizerSystemPrompt } from "./parsing";
import { createToolResultMessage, executeLocalTool, localToolDefinitions } from "./tools";
import type { AgentConfig, ChatMessage, ModelResponse, PlanExecuteResult, PlanExecuteStep, RunInput } from "./types";

async function executePlanStep(step: string, plan: string[], task: string, index: number, temperature: number, config: AgentConfig) {
  const systemPrompt = executorSystemPrompt(step, plan, task); const requestPayload = { model: config.model, temperature, messages: [{ role: "system" as const, content: systemPrompt }, { role: "user" as const, content: `Execute step ${index + 1}: ${step}` }], tools: localToolDefinitions, tool_choice: "auto" as const };
  const completion = await runChatCompletion(requestPayload, config); if (!completion.ok) return { requestPayload, responsePayload: completion.responsePayload, toolExecutions: [], followUpRequestPayload: null, followUpResponsePayload: null, stepResult: "" };
  const assistant = (completion.responsePayload as ModelResponse)?.choices?.[0]?.message; const toolExecutions = (assistant?.tool_calls ?? []).map(executeLocalTool); const toolMessages = toolExecutions.map(createToolResultMessage);
  if (!toolMessages.length) return { requestPayload, responsePayload: completion.responsePayload, toolExecutions, followUpRequestPayload: null, followUpResponsePayload: null, stepResult: assistant?.content ?? "" };
  const messages: ChatMessage[] = [{ role: "system", content: systemPrompt }, { role: "user", content: `Execute step ${index + 1}: ${step}` }, ...(assistant ? [assistant] : []), ...toolMessages]; const followUpRequestPayload = { model: config.model, temperature, messages }; const followUp = await runChatCompletion(followUpRequestPayload, config); const result = (followUp.responsePayload as ModelResponse)?.choices?.[0]?.message?.content ?? "";
  return { requestPayload, responsePayload: completion.responsePayload, toolExecutions, followUpRequestPayload, followUpResponsePayload: followUp.responsePayload, stepResult: result || assistant?.content || "" };
}

export async function runPlanExecute(input: RunInput, config: AgentConfig): Promise<PlanExecuteResult> {
  assertRunnable(input, config); const temperature = input.temperature ?? config.temperature; const startedAt = performance.now(); const users = input.messages.filter((m) => m.role === "user"); const originalTask = users[users.length - 1]?.content ?? input.messages.find((m) => m.content)?.content ?? "";
  const plannerRequestPayload = { model: config.model, temperature, messages: [{ role: "system" as const, content: plannerSystemPrompt }, { role: "user" as const, content: originalTask }] }; const planner = await runChatCompletion(plannerRequestPayload, config); if (!planner.ok) throw new Error(`DeepSeek planner request failed (${planner.status}).`); const plan = parsePlan((planner.responsePayload as ModelResponse)?.choices?.[0]?.message?.content ?? ""); const steps: PlanExecuteStep[] = [];
  for (let i = 0; i < plan.length; i += 1) { const result = await executePlanStep(plan[i], plan, originalTask, i, temperature, config); steps.push({ step: i + 1, description: plan[i], executorSystemPrompt: executorSystemPrompt(plan[i], plan, originalTask), executorRequestPayload: result.requestPayload, executorResponsePayload: result.responsePayload, toolExecutions: result.toolExecutions, followUpRequestPayload: result.followUpRequestPayload, followUpResponsePayload: result.followUpResponsePayload, stepResult: result.stepResult || `[Step ${i + 1} could not be completed — model returned no content]` }); }
  const synthesizerRequestPayload = { model: config.model, temperature, messages: [{ role: "system" as const, content: synthesizerSystemPrompt(originalTask, plan, steps.map((s) => s.stepResult)) }, { role: "user" as const, content: "Produce the final answer based on the plan and results above." }] }; const synthesis = await runChatCompletion(synthesizerRequestPayload, config); const finalAnswer = (synthesis.responsePayload as ModelResponse)?.choices?.[0]?.message?.content ?? "";
  return { baseUrl: config.baseUrl, model: config.model, durationMs: Math.round(performance.now() - startedAt), plannerRequestPayload, plannerResponsePayload: planner.responsePayload, plan, steps, synthesizerRequestPayload, synthesizerResponsePayload: synthesis.responsePayload, finalAnswer: finalAnswer || "Synthesis failed. See step results for details.", toolDefinitions: localToolDefinitions, ...(!synthesis.ok ? { error: "Synthesizer returned an error. Step results are available." } : {}) };
}
